"""Updated bike seed list per user request:
- Motorcycles: from https://www.innovativehonda.com/new-bikes.html?type=bikes
- Scooters: from https://www.innovativehonda.com/new-bikes.html?type=scooters
- EV: from https://www.honda2wheelersindia.com/e2w/products
Bikes split into 'motorcycle' (commuter/sport <=350cc), 'bigwing' (premium >=500cc),
'scooter' (Dio/Activa), 'ev' (Activa e:, QC1).
Each bike has color_options (list of names) and specifications (dict).
"""

SEED_BIKES = [
    # ---------------- MOTORCYCLES (commuter / sport, <=350cc) ----------------
    {"slug": "shine-100", "name": "Honda Shine 100", "category": "motorcycle", "price_from": 65446,
     "engine": "98.98 cc", "power": "7.38 bhp", "mileage": "65 kmpl",
     "description": "The most affordable Honda. Trust, quality, refinement — built for everyday commuting.",
     "image": "https://cdn.bikedekho.com/processedimages/honda/shine-100/source/shine-10069c50c83b8118.jpg",
     "color_options": ["Pearl Igneous Black", "Imperial Red Metallic", "Geny Grey Metallic"],
     "specifications": {"Displacement": "98.98 cc", "Max Power": "7.38 bhp @ 7,500 rpm", "Max Torque": "8.05 Nm @ 5,000 rpm",
                        "Mileage": "65 kmpl (claimed)", "Transmission": "4-speed", "Fuel Tank": "9 L",
                        "Front Brake": "Drum", "Rear Brake": "Drum", "Tyre Front": "80/100-18", "Tyre Rear": "80/100-18",
                        "Kerb Weight": "99 kg", "Seat Height": "786 mm", "Starter": "Kick & Self"}},

    {"slug": "shine-100-dx", "name": "Honda Shine 100 DX", "category": "motorcycle", "price_from": 71015,
     "engine": "98.98 cc", "power": "7.38 bhp", "mileage": "65 kmpl",
     "description": "Premium variant of Shine 100 with disc brake & alloy wheels for sharper styling.",
     "image": "https://cdn.bikedekho.com/processedimages/honda/shine-100-dx/source/shine-100-dx699ec4f4c3dbc.jpg",
     "color_options": ["Pearl Igneous Black", "Athletic Blue Metallic", "Imperial Red Metallic"],
     "specifications": {"Displacement": "98.98 cc", "Max Power": "7.38 bhp @ 7,500 rpm", "Max Torque": "8.05 Nm @ 5,000 rpm",
                        "Mileage": "65 kmpl (claimed)", "Transmission": "4-speed", "Fuel Tank": "9 L",
                        "Front Brake": "Disc 240 mm", "Rear Brake": "Drum", "Wheels": "Alloy",
                        "Kerb Weight": "101 kg", "Seat Height": "786 mm"}},

    {"slug": "livo", "name": "Honda Livo", "category": "motorcycle", "price_from": 81143,
     "engine": "109.51 cc", "power": "8.79 bhp", "mileage": "65 kmpl",
     "description": "Stylish 110cc commuter with class-leading mileage, refined engine and bold design.",
     "image": "https://cdn.bikedekho.com/processedimages/honda/2025-livo/source/2025-livo68ce4966676c3.jpg",
     "color_options": ["Pearl Igneous Black", "Sports Red", "Athletic Blue Metallic", "Geny Grey Metallic"],
     "specifications": {"Displacement": "109.51 cc", "Max Power": "8.79 bhp @ 7,500 rpm", "Max Torque": "9.30 Nm @ 5,500 rpm",
                        "Mileage": "65 kmpl (claimed)", "Transmission": "4-speed", "Fuel Tank": "9 L",
                        "Front Brake": "Drum/Disc", "Rear Brake": "Drum", "Tyre Front": "80/100-18", "Tyre Rear": "80/100-18",
                        "Kerb Weight": "115 kg", "Seat Height": "790 mm"}},

    {"slug": "shine", "name": "Honda Shine", "category": "motorcycle", "price_from": 82565,
     "engine": "123.94 cc", "power": "10.59 bhp", "mileage": "65 kmpl",
     "description": "India's No.1 125cc motorcycle. Refined power, smooth ride, dependable for years.",
     "image": "https://cdn.bikedekho.com/processedimages/honda/shine-bs6/source/shine-bs669c5026641b53.jpg",
     "color_options": ["Pearl Igneous Black", "Imperial Red Metallic", "Geny Grey Metallic", "Athletic Blue Metallic"],
     "specifications": {"Displacement": "123.94 cc", "Max Power": "10.59 bhp @ 7,500 rpm", "Max Torque": "11 Nm @ 6,000 rpm",
                        "Mileage": "65 kmpl (claimed)", "Transmission": "5-speed", "Fuel Tank": "10.5 L",
                        "Front Brake": "Drum/Disc 240 mm", "Rear Brake": "Drum 130 mm",
                        "Tyre Front": "80/100-18", "Tyre Rear": "80/100-18",
                        "Kerb Weight": "114 kg", "Seat Height": "790 mm"}},

    {"slug": "sp-125", "name": "Honda SP 125", "category": "motorcycle", "price_from": 89570,
     "engine": "123.94 cc", "power": "10.72 bhp", "mileage": "65 kmpl",
     "description": "Sporty, efficient, powerful — India's first BS-VI 125cc motorcycle with eSP technology.",
     "image": "https://cdn.bikedekho.com/processedimages/honda/sp125/source/sp12568a70d4bcf14e.jpg",
     "color_options": ["Sports Red", "Pearl Siren Blue", "Pearl Igneous Black", "Matte Marvel Blue Metallic"],
     "specifications": {"Displacement": "123.94 cc", "Max Power": "10.72 bhp @ 7,500 rpm", "Max Torque": "10.9 Nm @ 6,000 rpm",
                        "Mileage": "65 kmpl (claimed)", "Transmission": "5-speed", "Fuel Tank": "11 L",
                        "Front Brake": "Disc 240 mm", "Rear Brake": "Drum 130 mm",
                        "Kerb Weight": "117 kg", "Seat Height": "790 mm", "Starter": "Self"}},

    {"slug": "unicorn", "name": "Honda Unicorn", "category": "motorcycle", "price_from": 113000,
     "engine": "162.71 cc", "power": "12.91 bhp", "mileage": "60 kmpl",
     "description": "The gentleman's motorcycle. Smooth, powerful, reliable — a benchmark in 160cc segment.",
     "image": "https://cdn.bikedekho.com/processedimages/honda/2025-unicorn/source/2025-unicorn68ce4cf60ca10.jpg",
     "color_options": ["Pearl Igneous Black", "Imperial Red Metallic", "Matte Axis Grey Metallic"],
     "specifications": {"Displacement": "162.71 cc", "Max Power": "12.91 bhp @ 7,500 rpm", "Max Torque": "14 Nm @ 5,500 rpm",
                        "Mileage": "60 kmpl (claimed)", "Transmission": "5-speed", "Fuel Tank": "13 L",
                        "Front Brake": "Disc 240 mm", "Rear Brake": "Drum 130 mm",
                        "Kerb Weight": "140 kg", "Seat Height": "798 mm"}},

    {"slug": "cb125-hornet", "name": "Honda CB125 Hornet", "category": "motorcycle", "price_from": 115000,
     "engine": "123.94 cc", "power": "10.97 bhp", "mileage": "60 kmpl",
     "description": "Streetfighter styling in a 125cc package. Big-bike attitude for the urban rider.",
     "image": "https://cdn.bikedekho.com/processedimages/honda/cb125-hornet/source/cb125-hornet68ce5a73e6d9d.jpg",
     "color_options": ["Sports Red", "Pearl Igneous Black", "Matte Axis Grey Metallic"],
     "specifications": {"Displacement": "123.94 cc", "Max Power": "10.97 bhp @ 7,500 rpm", "Max Torque": "11.0 Nm @ 6,000 rpm",
                        "Mileage": "60 kmpl (claimed)", "Transmission": "5-speed", "Fuel Tank": "11 L",
                        "Front Brake": "Disc 276 mm", "Rear Brake": "Disc 220 mm",
                        "Kerb Weight": "125 kg", "Seat Height": "790 mm"}},

    {"slug": "sp160", "name": "Honda SP160", "category": "motorcycle", "price_from": 117000,
     "engine": "162.71 cc", "power": "13.27 bhp", "mileage": "55 kmpl",
     "description": "Sporty performance meets everyday practicality. Built for the daily thrill-seeker.",
     "image": "https://cdn.bikedekho.com/processedimages/honda/sp160/source/sp16068a70eb05f0f8.jpg",
     "color_options": ["Sports Red", "Pearl Igneous Black", "Matte Marvel Blue Metallic", "Mat Axis Grey Metallic"],
     "specifications": {"Displacement": "162.71 cc", "Max Power": "13.27 bhp @ 7,500 rpm", "Max Torque": "14.58 Nm @ 5,500 rpm",
                        "Mileage": "55 kmpl (claimed)", "Transmission": "5-speed", "Fuel Tank": "12 L",
                        "Front Brake": "Disc 276 mm", "Rear Brake": "Disc 220 mm (top), Drum (base)",
                        "Kerb Weight": "134 kg", "Seat Height": "790 mm"}},

    {"slug": "hornet-2-0", "name": "Honda Hornet 2.0", "category": "motorcycle", "price_from": 148000,
     "engine": "184.4 cc", "power": "17.03 bhp", "mileage": "45 kmpl",
     "description": "Premium streetfighter with aggressive design, USD forks, and thrilling performance.",
     "image": "https://cdn.bikedekho.com/processedimages/honda/hornet-20/source/hornet-2068a70d6ca9a5c.jpg",
     "color_options": ["Sports Red", "Matte Axis Grey Metallic", "Pearl Igneous Black", "Matte Marvel Blue Metallic"],
     "specifications": {"Displacement": "184.4 cc", "Max Power": "17.03 bhp @ 8,500 rpm", "Max Torque": "16.1 Nm @ 6,000 rpm",
                        "Mileage": "45 kmpl (claimed)", "Transmission": "5-speed", "Fuel Tank": "12 L",
                        "Front Suspension": "USD Forks", "Front Brake": "Petal Disc 276 mm", "Rear Brake": "Petal Disc 220 mm",
                        "ABS": "Single channel", "Kerb Weight": "142 kg", "Seat Height": "790 mm"}},

    {"slug": "cb300f-flex-fuel", "name": "Honda CB300F Flex-Fuel", "category": "motorcycle", "price_from": 156000,
     "engine": "293.52 cc", "power": "24 bhp", "mileage": "30 kmpl",
     "description": "India's first flex-fuel motorcycle. Runs on E20 to E85 ethanol blends — sustainable performance.",
     "image": "https://cdn.bikedekho.com/processedimages/honda/cb300f-flex-fuel/source/cb300f-flex-fuel68a8a85a3dca6.jpg",
     "color_options": ["Mat Marvel Blue Metallic", "Sports Red"],
     "specifications": {"Displacement": "293.52 cc", "Max Power": "24 bhp @ 7,500 rpm", "Max Torque": "25.9 Nm @ 5,500 rpm",
                        "Fuel Type": "Petrol + E20-E85 Flex-Fuel", "Transmission": "6-speed", "Fuel Tank": "14 L",
                        "Front Brake": "Disc 276 mm", "Rear Brake": "Disc 220 mm", "ABS": "Dual channel",
                        "Kerb Weight": "153 kg", "Seat Height": "789 mm"}},

    {"slug": "nx200", "name": "Honda NX200", "category": "motorcycle", "price_from": 159000,
     "engine": "184.4 cc", "power": "17.03 bhp", "mileage": "40 kmpl",
     "description": "Adventure-ready 200cc with long-travel suspension, dual-purpose tyres and rugged styling.",
     "image": "https://cdn.bikedekho.com/processedimages/honda/nx200/source/nx20068a8a5c7ad7d2.jpg",
     "color_options": ["Pearl Igneous Black", "Matte Axis Grey Metallic", "Matte Marvel Blue Metallic"],
     "specifications": {"Displacement": "184.4 cc", "Max Power": "17.03 bhp @ 8,500 rpm", "Max Torque": "16.1 Nm @ 6,000 rpm",
                        "Mileage": "40 kmpl (claimed)", "Transmission": "5-speed", "Fuel Tank": "12 L",
                        "Front Suspension": "Telescopic 31mm", "Rear Suspension": "Mono shock",
                        "Front Brake": "Disc 276 mm", "Rear Brake": "Disc 220 mm", "ABS": "Dual channel",
                        "Kerb Weight": "147 kg", "Seat Height": "810 mm"}},

    {"slug": "cb350", "name": "Honda CB350", "category": "motorcycle", "price_from": 197000,
     "engine": "348.36 cc", "power": "20.78 bhp", "mileage": "37 kmpl",
     "description": "Modern classic 350cc with retro charm, refined long-stroke engine and premium fit-finish.",
     "image": "https://cdn.bikedekho.com/processedimages/honda/cb350/source/cb35069c50c4bc5078.jpg",
     "color_options": ["Pearl Igneous Black", "Mat Marshal Green Metallic", "Precious Red Metallic"],
     "specifications": {"Displacement": "348.36 cc", "Max Power": "20.78 bhp @ 5,500 rpm", "Max Torque": "29.4 Nm @ 3,000 rpm",
                        "Mileage": "37 kmpl (claimed)", "Transmission": "5-speed", "Fuel Tank": "15 L",
                        "Front Brake": "Disc 310 mm", "Rear Brake": "Disc 240 mm", "ABS": "Dual channel",
                        "Kerb Weight": "181 kg", "Seat Height": "800 mm"}},

    {"slug": "cb350c", "name": "Honda CB350C", "category": "motorcycle", "price_from": 199000,
     "engine": "348.36 cc", "power": "20.78 bhp", "mileage": "37 kmpl",
     "description": "Classic-cruiser styling on the CB350 platform. Upright ergos, big tank, vintage soul.",
     "image": "https://cdn.bikedekho.com/processedimages/honda/cb350c/source/cb350c68ce5878b5cf6.jpg",
     "color_options": ["Pearl Igneous Black", "Imperial Red Metallic", "Mat Marshal Green Metallic"],
     "specifications": {"Displacement": "348.36 cc", "Max Power": "20.78 bhp @ 5,500 rpm", "Max Torque": "29.4 Nm @ 3,000 rpm",
                        "Mileage": "37 kmpl (claimed)", "Transmission": "5-speed", "Fuel Tank": "15 L",
                        "Front Brake": "Disc 310 mm", "Rear Brake": "Disc 240 mm", "ABS": "Dual channel",
                        "Kerb Weight": "181 kg", "Seat Height": "800 mm"}},

    # ---------------- BIG WING (premium >=500cc) ----------------
    {"slug": "nx500", "name": "Honda NX500", "category": "bigwing", "price_from": 632000,
     "engine": "471 cc", "power": "47 bhp", "mileage": "25 kmpl",
     "description": "Mid-size adventure tourer. Conquer highways and off-road trails with twin-cylinder smoothness.",
     "image": "https://cdn.bikedekho.com/processedimages/honda/nx500/source/nx50068a8a73f7f81d.jpg",
     "color_options": ["Grand Prix Red", "Mat Ballistic Black Metallic"],
     "specifications": {"Displacement": "471 cc", "Engine Type": "Parallel-twin, liquid-cooled", "Max Power": "47 bhp @ 8,600 rpm",
                        "Max Torque": "43.2 Nm @ 6,500 rpm", "Transmission": "6-speed", "Fuel Tank": "17.5 L",
                        "Front Suspension": "USD Forks 41mm", "Rear Suspension": "Pro-Link mono",
                        "Front Brake": "Twin Disc 296 mm", "Rear Brake": "Disc 240 mm", "ABS": "Dual channel",
                        "Kerb Weight": "199 kg", "Seat Height": "830 mm"}},

    {"slug": "cb750-hornet", "name": "Honda CB750 Hornet", "category": "bigwing", "price_from": 922000,
     "engine": "755 cc", "power": "90.5 bhp", "mileage": "20 kmpl",
     "description": "Streetfighter aggression with twin-cylinder torque. Honda's sharpest middleweight naked.",
     "image": "https://cdn.bikedekho.com/processedimages/honda/cb750-hornet/source/cb750-hornet68a8a59a4d72b.jpg",
     "color_options": ["Mat Iridium Grey Metallic", "Grand Prix Red", "Pearl Glare White"],
     "specifications": {"Displacement": "755 cc", "Engine Type": "Parallel-twin, liquid-cooled", "Max Power": "90.5 bhp @ 9,500 rpm",
                        "Max Torque": "75 Nm @ 7,250 rpm", "Transmission": "6-speed with quickshifter",
                        "Fuel Tank": "15.2 L", "Front Suspension": "USD Showa SFF-BP",
                        "Front Brake": "Twin Radial Disc 296 mm", "Rear Brake": "Disc 240 mm", "ABS": "Dual channel",
                        "Kerb Weight": "190 kg", "Seat Height": "795 mm"}},

    {"slug": "xl750-transalp", "name": "Honda XL750 Transalp", "category": "bigwing", "price_from": 1180000,
     "engine": "755 cc", "power": "90.5 bhp", "mileage": "22 kmpl",
     "description": "True 50/50 adventure tourer. 21-inch front wheel, long-travel suspension, ride modes for any terrain.",
     "image": "https://cdn.bikedekho.com/processedimages/honda/xl750-transalp/source/xl750-transalp68a8a8f146ca6.jpg",
     "color_options": ["Ross White", "Mat Ballistic Black Metallic"],
     "specifications": {"Displacement": "755 cc", "Engine Type": "Parallel-twin, liquid-cooled", "Max Power": "90.5 bhp @ 9,500 rpm",
                        "Max Torque": "75 Nm @ 7,250 rpm", "Transmission": "6-speed", "Fuel Tank": "16.9 L",
                        "Front Suspension": "USD Showa SFF-CA", "Rear Suspension": "Pro-Link mono",
                        "Front Brake": "Twin Disc 310 mm", "Rear Brake": "Disc 256 mm",
                        "Ride Modes": "Sport, Standard, Rain, Gravel, User", "Kerb Weight": "208 kg", "Seat Height": "850 mm"}},

    {"slug": "cb1000-hornet-sp", "name": "Honda CB1000 Hornet SP", "category": "bigwing", "price_from": 1329000,
     "engine": "1000 cc", "power": "157 bhp", "mileage": "16 kmpl",
     "description": "Liter-class streetfighter with Öhlins suspension, Brembo Stylema and CBR1000RR-derived engine.",
     "image": "https://cdn.bikedekho.com/processedimages/honda/cb1000-hornet-sp/source/cb1000-hornet-sp68a8a4a6a21ed.jpg",
     "color_options": ["Mat Ballistic Black Metallic", "Grand Prix Red"],
     "specifications": {"Displacement": "1000 cc", "Engine Type": "Inline-4, liquid-cooled", "Max Power": "157 bhp @ 11,000 rpm",
                        "Max Torque": "107 Nm @ 9,000 rpm", "Transmission": "6-speed with quickshifter",
                        "Fuel Tank": "17 L", "Front Suspension": "Öhlins TTX 43mm USD",
                        "Front Brake": "Twin Brembo Stylema 4-pot", "Rear Brake": "Brembo single piston",
                        "Ride Modes": "5 modes + Track + 3 user", "Kerb Weight": "212 kg", "Seat Height": "809 mm"}},

    # ---------------- SCOOTERS ----------------
    {"slug": "dio", "name": "Honda Dio", "category": "scooter", "price_from": 74107,
     "engine": "109.51 cc", "power": "7.65 bhp", "mileage": "55 kmpl",
     "description": "Youthful styling, vibrant graphics. Keep Dio'ing it — the scooter that defined a generation.",
     "image": "https://cdn.bikedekho.com/processedimages/honda/2025-dio/source/2025-dio69c3ced694db2.jpg",
     "color_options": ["Pearl Siren Blue", "Sports Red", "Pearl Igneous Black", "Matte Axis Grey Metallic", "Pearl Spartan Red"],
     "specifications": {"Displacement": "109.51 cc", "Max Power": "7.65 bhp @ 8,000 rpm", "Max Torque": "9 Nm @ 5,500 rpm",
                        "Mileage": "55 kmpl (claimed)", "Transmission": "Automatic CVT", "Fuel Tank": "5.3 L",
                        "Front Brake": "Drum 130 mm / Disc 190 mm", "Rear Brake": "Drum 130 mm",
                        "Tyres": "90/100-12 (tubeless)", "Kerb Weight": "104 kg", "Seat Height": "765 mm",
                        "Underseat Storage": "18 L", "Starter": "Self & Kick"}},

    {"slug": "activa-6g", "name": "Honda Activa 6G", "category": "scooter", "price_from": 77892,
     "engine": "109.51 cc", "power": "7.68 bhp", "mileage": "47 kmpl",
     "description": "India's most trusted scooter. Now smarter with H-Smart key, idling stop and silent start.",
     "image": "https://cdn.bikedekho.com/processedimages/honda/activa-6g/source/activa-6g68a6fb7b20bd3.jpg",
     "color_options": ["Pearl Precious White", "Pearl Igneous Black", "Matte Axis Grey Metallic", "Decent Blue Metallic", "Rebel Red Metallic"],
     "specifications": {"Displacement": "109.51 cc", "Max Power": "7.68 bhp @ 8,000 rpm", "Max Torque": "8.79 Nm @ 5,500 rpm",
                        "Mileage": "47 kmpl (claimed)", "Transmission": "Automatic CVT", "Fuel Tank": "5.3 L",
                        "Front Brake": "Drum 130 mm", "Rear Brake": "Drum 130 mm",
                        "Tyres": "90/100-12 tubeless", "Kerb Weight": "107 kg", "Seat Height": "765 mm",
                        "Smart Key": "H-Smart (DLX variant)", "Starter": "Self & Kick"}},

    {"slug": "activa-125", "name": "Honda Activa 125", "category": "scooter", "price_from": 92502,
     "engine": "123.92 cc", "power": "8.18 bhp", "mileage": "47 kmpl",
     "description": "Premium family scooter with H-Smart keyless experience and refined power for family duties.",
     "image": "https://cdn.bikedekho.com/processedimages/honda/2025-activa-125/source/2025-activa-12568ce3a43579a4.jpg",
     "color_options": ["Pearl Precious White", "Pearl Igneous Black", "Matte Sangria Red Metallic", "Matte Steel Black Metallic"],
     "specifications": {"Displacement": "123.92 cc", "Max Power": "8.18 bhp @ 6,500 rpm", "Max Torque": "10.4 Nm @ 5,000 rpm",
                        "Mileage": "47 kmpl (claimed)", "Transmission": "Automatic CVT", "Fuel Tank": "5.3 L",
                        "Front Brake": "Drum 130 mm / Disc 190 mm", "Rear Brake": "Drum 130 mm",
                        "Tyres": "90/90-12 (front), 90/100-10 (rear)", "Kerb Weight": "111 kg", "Seat Height": "765 mm",
                        "Underseat Storage": "18 L", "Smart Key": "H-Smart (DLX & H-Smart variant)"}},

    {"slug": "dio-125", "name": "Honda Dio 125", "category": "scooter", "price_from": 92817,
     "engine": "123.92 cc", "power": "8.16 bhp", "mileage": "48 kmpl",
     "description": "Bold. Sporty. Faster. The premium youth scooter with H-Smart key and TFT-style console.",
     "image": "https://cdn.bikedekho.com/processedimages/honda/dio-125/source/dio-12568ce48fa5ac54.jpg",
     "color_options": ["Pearl Spartan Red", "Pearl Igneous Black", "Matte Marvel Blue Metallic", "Matte Axis Grey Metallic"],
     "specifications": {"Displacement": "123.92 cc", "Max Power": "8.16 bhp @ 6,500 rpm", "Max Torque": "10.4 Nm @ 5,000 rpm",
                        "Mileage": "48 kmpl (claimed)", "Transmission": "Automatic CVT", "Fuel Tank": "5.3 L",
                        "Front Brake": "Disc 190 mm", "Rear Brake": "Drum 130 mm",
                        "Wheels": "Alloy 12-inch front", "Kerb Weight": "111 kg", "Seat Height": "765 mm",
                        "Smart Key": "H-Smart"}},

    # ---------------- EV ----------------
    {"slug": "activa-e", "name": "Honda Activa e:", "category": "ev", "price_from": 119912,
     "engine": "Electric (swappable battery)", "power": "6 kW", "mileage": "102 km / charge",
     "description": "Honda's first electric scooter for India. Zero emissions, swappable battery, pure Activa DNA.",
     "image": "https://www.honda2wheelersindia.com/content/dam/e2w/apac/india/products/activa-e/image/activae.png",
     "color_options": ["Pearl Misty White", "Pearl Igneous Black", "Pearl Serenity Blue", "Pearl Shallow Blue"],
     "specifications": {"Motor Type": "PMSM (Permanent Magnet Synchronous)", "Peak Power": "6 kW",
                        "Battery": "Swappable Honda Mobile Power Pack e: × 2", "Range (IDC)": "102 km",
                        "Top Speed": "80 km/h", "Charging": "Battery swap at Honda e: stations",
                        "Drive Modes": "ECON, STANDARD, SPORT", "Connected Features": "App connectivity",
                        "Brakes": "CBS (Combi Brake System)", "Tyres": "Tubeless 12-inch",
                        "Wheelbase": "1310 mm", "Kerb Weight": "118 kg"}},

    {"slug": "qc1", "name": "Honda QC1", "category": "ev", "price_from": 90487,
     "engine": "Electric (fixed battery)", "power": "1.8 kW", "mileage": "80 km / charge",
     "description": "Compact, efficient, affordable. Perfect city companion with fixed battery & home charging.",
     "image": "https://www.honda2wheelersindia.com/content/dam/e2w/apac/india/products/qc1/image/qc1.png",
     "color_options": ["Pearl Serenity Blue", "Pearl Misty White", "Pearl Igneous Black", "Matte Foggy Silver Metallic"],
     "specifications": {"Motor Type": "PMSM (Permanent Magnet Synchronous)", "Peak Power": "1.8 kW",
                        "Battery": "Fixed Lithium-ion 1.5 kWh", "Range (IDC)": "80 km",
                        "Top Speed": "50 km/h", "Charging": "Home charger (~6 hrs full)",
                        "Drive Modes": "ECON, STANDARD", "Brakes": "CBS",
                        "Tyres": "Tubeless 12-inch", "Underseat Storage": "26 L",
                        "Kerb Weight": "90 kg", "Seat Height": "765 mm"}},
]
